version: "3.9"
services:
  # Base de données MongoDB
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db

  # Backend
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/addressbook
    depends_on:
      - mongo

  # Frontend
  frontend:
    build: ./frontend
    depends_on:
      - backend

  # Proxy
  nginx:
    build: ./frontend
    ports:
      - "3001:3001"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
