version: "3.9"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/addressbook
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    stdin_open: true
    tty: true
    depends_on:
      - backend
